sql: !apply:roughrider.sqlalchemy.component.SQLAlchemyEngine.from_url
  name: sql
  url: sqlite:///example.db

app: !new:api.app.Application
  sql_engine: !ref <sql>

loaders:
  - !name:horsebox.utils.modules_loader
    - !module:api.endpoints
  - !name:api.models.create_sql_tables
    - !ref <sql>

runner: !name:bjoern.run
  host: 0.0.0.0
  port: 8080
  reuse_port: true
  wsgi_app: !ref <app>
